### ISSUE TITLE
S3 bucket invalid name

### ISSUE THREAD

**Issue by sharonsahadevan** [cloudposse/terraform-aws-elastic-beanstalk-environment#169]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
S3 bucket is not getting created - it returns 400 response with "Invalid name"  error

## Expected Behavior
elb log s3 bucket should be created

![image](https://user-images.githubusercontent.com/29514761/109693780-131c1480-7bb0-11eb-9a51-af9874685d93.png)

**Comment by florian0410** [comment]
What is your S3 bucket name in this example ?

**Comment by acidix** [comment]
Same problem here, the bucket name that is being tried is:

```
+ bucket                      = "-eb-loadbalancer-logs"
```

Seems like `module.this.id` is empty at this point.

```
  bucket        = "${module.this.id}-eb-loadbalancer-logs"
```

**Comment by florian0410** [comment]
Maybe because it already exists since S3 bucket are Global in AWS.

@acidix you are instantiating the module without specifying a CloudPosse context object so it will stay default since instantiated by the module.
https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/master/context.tf

You can alternatively specify the following variables for naming it : namespace, environment, stage, name and attributes for customs.

For more infos on the context object and idea go see the repo: https://github.com/cloudposse/terraform-null-label

**Comment by nitrocode** [comment]
It's probably as simple as setting the `name` argument on the module.
